In [5]:
# the meaningfulness of '__init__'
#
class A(object):
    i=22
    # self is defined overhere
    def __init__(self):
        self.x = 'Hello'
    #self is defined by __init__, so only 'foo' needs to be defined in method_a 
    def method_a(self, foo):
        print (self.x + ' ' + foo)

In [8]:
a=A()
a.i

22

In [15]:
a.method_a('Sailor!')

Hello Sailor!


# Draft 

In [ ]:
!pip install -r requirements.txt --user

  Using cached asttokens-2.2.1-py2.py3-none-any.whl (26 kB)
  Using cached attrs-22.2.0-py3-none-any.whl (60 kB)
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
  Using cached comm-0.1.2-py3-none-any.whl (6.5 kB)
  Using cached debugpy-1.6.6-cp39-cp39-win_amd64.whl (4.8 MB)
  Using cached exceptiongroup-1.1.0-py3-none-any.whl (14 kB)
  Using cached executing-1.2.0-py2.py3-none-any.whl (24 kB)
  Using cached importlib_metadata-6.0.0-py3-none-any.whl (21 kB)
  Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
  Using cached ipykernel-6.21.2-py3-none-any.whl (149 kB)
  Using cached ipython-8.10.0-py3-none-any.whl (784 kB)
  Using cached jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)
  Using cached jupyter_client-8.0.3-py3-none-any.whl (102 kB)
  Using cached jupyter_core-5.2.0-py3-none-any.whl (94 kB)
  Using cached numpy-1.24.2-cp39-cp39-win_amd64.whl (14.9 MB)
  Using cached packaging-23.0-py3-none-any.whl (42 kB)
  Using cached platformdirs-3.0.0-py3-none-any.whl (14 kB)
  U

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.6.0 requires daal==2021.4.0, which is not installed.
anaconda-project 0.11.1 requires ruamel-yaml, which is not inst

In [20]:
import numpy as np
import MixtureOptDesign

In [21]:
#input
    #design 
    #beta 
    #order
    #q=3  j=2 s=8

# Data
data = [0.3897873, 0.6292498, 0.7009263, 0.4262842, 0.246073770, 0.48413014, 0.2913878, 0.7201046335,
        0.4982357, 0.007519965, 0.2505569, 0.1549670, 0.5415304, 0.3639989, 0.04235179, 0.3279013,
        0.2375383, 0.1180457, 0.2000333, 0.2569634, 0.749005428, 0.03588967, 0.3591402, 0.0009022414,
        0.2549352, 0.636080256, 0.4460236, 0.6877322, 0.2635403, 0.3727396, 0.44510098, 0.2701244,
        0.3726744, 0.2527044, 0.0990404, 0.3167524, 0.004920801, 0.47998018, 0.3494720, 0.2789931250,
        0.2468291, 0.356399779, 0.3034196, 0.1573008, 0.1949293, 0.2632615, 0.51254723, 0.4019743]

# Convert to a numpy array of shape (3, 2, 8)
design = np.array(data).reshape((3, 2, 8))

In [24]:
type(design)

numpy.ndarray

In [32]:
beta = MixtureOptDesign.generate_beta_params(num_params=7,q=3)
beta_star, beta_2, beta_3 = MixtureOptDesign.get_beta_coefficients(beta,3,3)

In [47]:
print('beta:'+' '+str(beta))
print()
print('beta_star:'+' '+str(beta_star)+ ' '+ str(len(beta_star)))
print()
print('beta_2:'+' '+str(beta_2)+ ' '+ str(len(beta_2)))
print()
print('beta_3:'+' '+str(beta_3)+ ' '+ str(len(beta_3)))

beta: [-1.09880992 -1.48990645 -0.88961739 -0.05820392 -0.69135755 -0.43193993]

beta_star: [-1.09880992 -1.48990645] 2

beta_2: [-0.88961739 -0.05820392 -0.69135755] 3

beta_3: [-0.43193993] 1


In [57]:
#utility and choice_probability
U = MixtureOptDesign.get_utilities(design,beta_star,beta_2,beta_3,3)
P = MixtureOptDesign.get_choice_probabilities(U)

In [58]:
U

array([[-0.99079913, -0.9940318 , -1.23344711, -1.06971059, -1.55440751,
        -0.64000156, -1.10100958, -0.80534493],
       [-1.14234606, -1.11989878, -1.19283631, -1.39343798, -1.20191233,
        -1.20798118, -0.90128955, -0.98266204]])

In [60]:
P

array([[0.53781439, 0.53142527, 0.4898487 , 0.58023238, 0.41277748,
        0.63829685, 0.4502353 , 0.54421349],
       [0.46218561, 0.46857473, 0.5101513 , 0.41976762, 0.58722252,
        0.36170315, 0.5497647 , 0.45578651]])

In [61]:
model_array = MixtureOptDesign.get_model_matrix(design,3)

In [64]:
model_array.shape

(6, 2, 8)

In [68]:
#model_array vs design
design
model_array

array([[[0.3897873 , 0.6292498 , 0.7009263 , 0.4262842 , 0.24607377,
         0.48413014, 0.2913878 , 0.72010463],
        [0.4982357 , 0.00751996, 0.2505569 , 0.154967  , 0.5415304 ,
         0.3639989 , 0.04235179, 0.3279013 ]],

       [[0.2375383 , 0.1180457 , 0.2000333 , 0.2569634 , 0.74900543,
         0.03588967, 0.3591402 , 0.00090224],
        [0.2549352 , 0.63608026, 0.4460236 , 0.6877322 , 0.2635403 ,
         0.3727396 , 0.44510098, 0.2701244 ]],

       [[0.3726744 , 0.2527044 , 0.0990404 , 0.3167524 , 0.0049208 ,
         0.47998018, 0.349472  , 0.27899313],
        [0.2468291 , 0.35639978, 0.3034196 , 0.1573008 , 0.1949293 ,
         0.2632615 , 0.51254723, 0.4019743 ]]])

In [70]:
information_matrix=MixtureOptDesign.get_information_matrix_mnl(design=design,order=3,beta=beta)

In [71]:
information_matrix.shape

(6, 6)

In [72]:
#optimal design

b = MixtureOptDesign.CoordinateExchangeIOptimal(design,order=3,n_points=100,iteration=10)

In [87]:
b.get_design()
optimal_design=b.optimize_design()

In [95]:
print(str(optimal_design.shape)) 
print()
print(optimal_design)

(3, 2, 8)

[[[0.         0.50505051 0.         1.         0.         0.
   0.         0.        ]
  [0.56565657 0.02020202 0.33041009 0.1010101  0.         0.33333333
   0.         0.62626263]]

 [[0.         0.49494949 0.         0.         1.         0.
   0.         0.61616162]
  [0.         0.02443171 0.34343434 0.         0.11111111 0.34245702
   0.58585859 0.        ]]

 [[1.         0.         1.         0.         0.         1.
   1.         0.38383838]
  [0.43434343 0.95536627 0.32615568 0.8989899  0.88888889 0.32420965
   0.41414141 0.37373737]]]
